"""Build a Markdown report from a persisted design run + its molecules.

A human-readable summary: goal, plan/constraints, a candidate property table, the
execution trace, and the agent's explanation — all sourced from stored provenance.
"""
from __future__ import annotations


def _fmt_constraints(constraints: dict) -> str:
    if not constraints:
        return "_none_"
    parts = []
    if constraints.get("mw_max") is not None:
        parts.append(f"MW ≤ {constraints['mw_max']}")
    if constraints.get("logp_min") is not None:
        parts.append(f"logP ≥ {constraints['logp_min']}")
    if constraints.get("logp_max") is not None:
        parts.append(f"logP ≤ {constraints['logp_max']}")
    if constraints.get("exclude_pains"):
        parts.append("no PAINS")
    if constraints.get("require_lipinski"):
        parts.append("Lipinski-compliant")
    return ", ".join(parts) or "_none_"


def build_markdown(run: dict, molecules: list[dict]) -> str:
    parent = next((m for m in molecules if m.get("source") == "user"), None)
    candidates = [m for m in molecules if m.get("source") == "generated"]
    plan = run.get("plan") or {}
    constraints = plan.get("constraints") or {}
    models = run.get("models_used") or {}
    trace = run.get("trace") or []

    lines: list[str] = []
    lines.append(f"# Design report — {run.get('goal_text', '')}\n")
    lines.append(f"- **Run ID:** `{run.get('id', 'n/a')}`")
    lines.append(f"- **Created:** {run.get('created_at', 'n/a')}")
    lines.append(f"- **Models used:** {', '.join(f'{k}={v}' for k, v in models.items()) or 'offline mock'}")
    if parent:
        lines.append(f"- **Parent:** `{parent['canonical_smiles']}`")
    lines.append("")

    lines.append("## Plan")
    lines.append(f"- **Max analogs:** {plan.get('max_analogs', 'n/a')}")
    lines.append(f"- **Constraints:** {_fmt_constraints(constraints)}")
    if plan.get("rationale"):
        lines.append(f"- **Rationale:** {plan['rationale']}")
    lines.append("")

    lines.append("## Candidates")
    lines.append(f"_{len(candidates)} generated and stored (passing the firewall + filters)._\n")
    if candidates:
        lines.append("| # | SMILES | MW | logP | TPSA | QED | Lipinski | PAINS |")
        lines.append("|---|--------|----|------|------|-----|----------|-------|")
        for i, c in enumerate(candidates, 1):
            p = c.get("properties") or {}
            lines.append(
                f"| {i} | `{c['canonical_smiles']}` "
                f"| {p.get('mw', '—')} | {p.get('logp', '—')} | {p.get('tpsa', '—')} "
                f"| {p.get('qed', '—')} "
                f"| {'pass' if p.get('lipinski_pass') else '—'} "
                f"| {'yes' if p.get('has_pains') else 'no'} |"
            )
        lines.append("")

    if trace:
        lines.append("## Execution trace")
        lines.append("| Step | Tool | Summary | Duration (ms) | Cache |")
        lines.append("|------|------|---------|---------------|-------|")
        for t in trace:
            lines.append(
                f"| {t.get('step', '')} | `{t.get('tool', '')}@{t.get('tool_version', '')}` "
                f"| {t.get('summary', '')} | {t.get('duration_ms', '')} "
                f"| {'hit' if t.get('cache_hit') else '—'} |"
            )
        lines.append("")

    if run.get("explanation"):
        lines.append("## Agent explanation")
        lines.append(run["explanation"])
        lines.append("")

    lines.append("---")
    lines.append("_Generated by Glowsky from stored run provenance. Structures were "
                 "validated and canonicalized by the deterministic firewall before storage._")
    return "\n".join(lines) + "\n"
