"""add libraries and library memberships

Revision ID: cf931554414c
Revises: 11fad528ae5a
Create Date: 2026-06-14 19:05:56.657004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf931554414c'
down_revision: Union[str, Sequence[str], None] = '11fad528ae5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('columns_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_libraries_project_id'), ['project_id'], unique=False)

    op.create_table('library_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('molecule_id', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_memberships_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_memberships_molecule_id'), ['molecule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_memberships_molecule_id'))
        batch_op.drop_index(batch_op.f('ix_library_memberships_library_id'))

    op.drop_table('library_memberships')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_project_id'))
        batch_op.drop_index(batch_op.f('ix_libraries_org_id'))

    op.drop_table('libraries')
    # ### end Alembic commands ###
