"""add llm provider credentials and route overrides

Revision ID: f68490608234
Revises: cf931554414c
Create Date: 2026-06-15 00:25:40.109408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68490608234'
down_revision: Union[str, Sequence[str], None] = 'cf931554414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', name='uq_org_provider')
    )
    with op.batch_alter_table('llm_provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_provider_credentials_org_id'), ['org_id'], unique=False)

    op.create_table('model_route_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('task_class', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'task_class', name='uq_org_taskclass')
    )
    with op.batch_alter_table('model_route_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_route_overrides_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_route_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_route_overrides_org_id'))

    op.drop_table('model_route_overrides')
    with op.batch_alter_table('llm_provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_provider_credentials_org_id'))

    op.drop_table('llm_provider_credentials')
    # ### end Alembic commands ###
